name: Build Grid2

on:
  workflow_dispatch:
    inputs:
      retail:
        type: boolean
        description: Retail
      retailtest:
        type: boolean
        description: Retail Test

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 200

      - name: Retail Test Package
        if: ${{ inputs.retailtest }}
        uses: BigWigsMods/packager@master
        with:
          args: -g retail -m .pkgmeta-retail
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Retail Package
        if: ${{ inputs.retail }}
        uses: BigWigsMods/packager@master
        with:
          args: -g retail -m .pkgmeta-retail
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
